name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      
      - name: compile
          run: bash ./pack.sh "build"